services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx json-server --watch data/sampledata.json --port 8000"
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge